# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.widgets.com:
    container_name: orderer.widgets.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/widgets.com/orderers/orderer.widgets.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/widgets.com/orderers/orderer.widgets.com/tls/:/var/hyperledger/orderer/tls
        - orderer.widgets.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.warehouse.widgets.com:
    container_name: peer0.warehouse.widgets.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.warehouse.widgets.com
      - CORE_PEER_ADDRESS=peer0.warehouse.widgets.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.warehouse.widgets.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.warehouse.widgets.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.warehouse.widgets.com:7051
      - CORE_PEER_LOCALMSPID=WarehouseMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/warehouse.widgets.com/peers/peer0.warehouse.widgets.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/warehouse.widgets.com/peers/peer0.warehouse.widgets.com/tls:/etc/hyperledger/fabric/tls
        - peer0.warehouse.widgets.com:/var/hyperledger/production
    ports:
      - 7051:7051

  peer1.warehouse.widgets.com:
    container_name: peer1.warehouse.widgets.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.warehouse.widgets.com
      - CORE_PEER_ADDRESS=peer1.warehouse.widgets.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.warehouse.widgets.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.warehouse.widgets.com:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.warehouse.widgets.com:7051
      - CORE_PEER_LOCALMSPID=WarehouseMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/warehouse.widgets.com/peers/peer1.warehouse.widgets.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/warehouse.widgets.com/peers/peer1.warehouse.widgets.com/tls:/etc/hyperledger/fabric/tls
        - peer1.warehouse.widgets.com:/var/hyperledger/production

    ports:
      - 8051:8051

  peer0.iad-factory.widgets.com:
    container_name: peer0.iad-factory.widgets.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.iad-factory.widgets.com
      - CORE_PEER_ADDRESS=peer0.iad-factory.widgets.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.iad-factory.widgets.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.iad-factory.widgets.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.iad-factory.widgets.com:10051
      - CORE_PEER_LOCALMSPID=IADFactoryMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/iad-factory.widgets.com/peers/peer0.iad-factory.widgets.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/iad-factory.widgets.com/peers/peer0.iad-factory.widgets.com/tls:/etc/hyperledger/fabric/tls
        - peer0.iad-factory.widgets.com:/var/hyperledger/production
    ports:
      - 9051:9051

  peer1.iad-factory.widgets.com:
    container_name: peer1.iad-factory.widgets.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.iad-factory.widgets.com
      - CORE_PEER_ADDRESS=peer1.iad-factory.widgets.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer1.iad-factory.widgets.com:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.iad-factory.widgets.com:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.iad-factory.widgets.com:9051
      - CORE_PEER_LOCALMSPID=IADFactoryMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/iad-factory.widgets.com/peers/peer1.iad-factory.widgets.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/iad-factory.widgets.com/peers/peer1.iad-factory.widgets.com/tls:/etc/hyperledger/fabric/tls
        - peer1.iad-factory.widgets.com:/var/hyperledger/production
    ports:
      - 10051:10051
